const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Senóide: 0},
	{plataforma: 0},
	{roboVida: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{DestruirExternamente: 0},
	{robo: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Projétil: 0},
	{bala: 0},
	{tempoderecarga: 0},
	{morto: 0},
	{podeAtirar: 0},
	{vidainimigo: 0},
	{CampoDeVisão: 0},
	{inimigo: 0},
	{Áudio: 0},
	{tiroInimigo: 0},
	{barraLateral: 0},
	{tempoderecarga2: 0},
	{vidaInimigo2: 0},
	{inimigo2: 0},
	{tirodoinimigo2: 0},
	{botaoJOGAR: 0},
	{Física: 0},
	{paredeDura: 0},
	{NaveInimiga: 0},
	{barraDeVida: 0},
	{plataformaFinal: 0},
	{Senóide2: 0},
	{pisoFinal: 0},
	{boosderecarga: 0},
	{vidaboos: 0},
	{RestritoAoLayout: 0},
	{BOOS: 0},
	{pisoMovel: 0},
	{fundo: 0},
	{tiroboos: 0},
	{gameover: 0},
	{BotaoVoltar: 0},
	{menu: 0},
	{vocevenceu: 0},
	{fundojogo: 0},
	{jogarnovamente: 0},
	{FonteDeSprites: 0}
];

self.InstanceType = {
	plataforma: class extends self.ISpriteInstance {},
	robo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	bala: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	tiroInimigo: class extends self.ISpriteInstance {},
	barraLateral: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	tirodoinimigo2: class extends self.ISpriteInstance {},
	botaoJOGAR: class extends self.ISpriteFontInstance {},
	paredeDura: class extends self.ISpriteInstance {},
	NaveInimiga: class extends self.ISpriteInstance {},
	barraDeVida: class extends self.ISpriteInstance {},
	plataformaFinal: class extends self.ISpriteInstance {},
	pisoFinal: class extends self.ISpriteInstance {},
	BOOS: class extends self.ISpriteInstance {},
	pisoMovel: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	tiroboos: class extends self.ISpriteInstance {},
	vidaboos: class extends self.ISpriteInstance {},
	vidainimigo: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	BotaoVoltar: class extends self.ISpriteFontInstance {},
	menu: class extends self.ISpriteInstance {},
	vocevenceu: class extends self.ISpriteInstance {},
	fundojogo: class extends self.ISpriteInstance {},
	jogarnovamente: class extends self.ISpriteFontInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {}
}